service: apollo-lambda
provider:
  name: aws
  runtime: nodejs18.x
  httpApi:
    cors: true
functions:
  graphql:
    handler: dist/server.graphqlHandler 
    events:
      - httpApi:
          path: /
          method: POST
      - httpApi:
          path: /
          method: GET